create table categories (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    primary key (id)
);

create table companies (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    description text not null,
    logo bytea not null,
    type varchar(255) not null,
    primary key (id)
);

create table users(
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(255) not null,
    primary key (id)
);

create table announcements (
    id bigint generated by default as identity,
    title varchar(255) not null,
    location varchar(255) not null,
    start_time timestamp not null,
    image bytea not null,
    organization_id bigint not null,
    price money,
    description text not null,
    href varchar(255),
    reviewer_id bigint not null,
    primary key (id)
);

create table announcement_categories(
    announcement_id bigint not null,
    category_id bigint not null
);

alter table announcements add constraint constraints1 foreign key (organization_id) references companies;
alter table announcements add constraint constraints2 foreign key (reviewer_id) references users;
alter table announcement_categories add constraint constraints3 foreign key (announcement_id) references announcements;
alter table announcement_categories add constraint constraints4 foreign key (category_id) references categories;

